export const STREAMER_ITEM_TYPES = {
    object: 0,
    pickup: 1,
    checkpoint: 2,
    raceCheckpoint: 3,
    mapIcon: 4,
    textLabel: 5,
    area: 6,
    actor: 7,
} as const

export type StreamerItemType = keyof typeof STREAMER_ITEM_TYPES

export const STREAMER_ITEM_DATA = {
    areaId: 0,
    attachedObject: 1,
    attachedPlayer: 2,
    attachedVehicle: 3,
    attachOffsetX: 4,
    attachOffsetY: 5,
    attachOffsetZ: 6,
    attachRotX: 7,
    attachRotY: 8,
    attachRotZ: 9,
    attachX: 10,
    attachY: 11,
    attachZ: 12,
    color: 13,
    drawDistance: 14,
    extraId: 15,
    health: 16,
    interiorId: 17,
    invulnerable: 18,
    maxX: 19,
    maxY: 20,
    maxZ: 21,
    minX: 22,
    minY: 23,
    minZ: 24,
    modelId: 25,
    moveRotX: 26,
    moveRotY: 27,
    moveRotZ: 28,
    moveSpeed: 29,
    moveX: 30,
    moveY: 31,
    moveZ: 32,
    nextX: 33,
    nextY: 34,
    nextZ: 35,
    playerId: 36,
    priority: 37,
    rotation: 38,
    rotX: 39,
    rotY: 40,
    rotZ: 41,
    size: 42,
    streamDistance: 43,
    style: 44,
    syncRotation: 45,
    testLOS: 46,
    type: 47,
    worldId: 48,
    x: 49,
    y: 50,
    z: 51,
} as const

export type StreamerItemData = keyof typeof STREAMER_ITEM_DATA
